let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.9279, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4678, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.2301, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1657, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.1215, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.099, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1979, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.614, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.3096, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.221, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.3377, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0553, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1053, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1703, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0341, "optimal":"yes"} ]}; 
