
*LABS from recycled HDPE
A('','')=
A('','')=
A('','')=
A('','')=
A('','')=


*LABS from recycled LDPE
A('','')=
A('','')=
A('','')=
A('','')=
A('','')=


*LABS substituted product
A('','')=
A('','')=
A('','')=
A('','')=
A('','')=
B('','')=
B('','')=
B('','')=
B('','')=
B('','')=

*pyrolysis of HDPE
A('','')=
A('','')=
A('','')=
A('','')=
A('','')=


*pyrolysis of LDPE
A('','')=
A('','')=
A('','')=
A('','')=
A('','')=


*C3 gas substituted product
A('','')=
A('','')=
A('','')=
A('','')=
A('','')=
B('','')=
B('','')=
B('','')=
B('','')=
B('','')=

* Liquid fuel substituted product
A('','')=
A('','')=
A('','')=
A('','')=
A('','')=
B('','')=
B('','')=
B('','')=
B('','')=
B('','')=


* Residue substituted product
A('','')=
A('','')=
A('','')=
A('','')=
A('','')=
B('','')=
B('','')=
B('','')=
B('','')=
B('','')=


*Tolune production utility
A('','')=
A('','')=
A('','')=
A('','')=
A('','')=
B('','')=
B('','')=
B('','')=
B('','')=
B('','')=


*PLA recycling using Lipase
A('','')=
A('','')=
A('','')=
A('','')=
A('','')=
B('','')=
B('','')=
B('','')=
B('','')=
B('','')=


*PLA recycling using mononitrile clay
A('','')=
A('','')=
A('','')=
A('','')=
A('','')=
B('','')=
B('','')=
B('','')=
B('','')=
B('','')=

*PLA recycling hydrolysis
A('','')=
A('','')=
A('','')=
A('','')=
A('','')=
B('','')=
B('','')=
B('','')=
B('','')=
B('','')=


*PLA recycling alcoholysis
A('','')=
A('','')=
A('','')=
A('','')=
A('','')=
B('','')=
B('','')=
B('','')=
B('','')=
B('','')=

