let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name": "Losses"},
{"name":"Value-chain Upstream"} 
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0051, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":2.2822, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.1046, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.0036, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.005, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":2.1111, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2844, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0255, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.8943, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1699, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.3343, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":1.4862, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0681, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0023, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0033, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.535, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.8174, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.1338, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0232, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0375, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0075, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.0009, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0013, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0002, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.0026, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0005, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0002, "optimal":"yes"} ,
{"source":"Value-chain Upstream", "target":"HDPE", "value":0.001, "optimal":"yes"} ,
{"source":"Value-chain Upstream", "target":"LDPE", "value":0.001, "optimal":"yes"} ,
{"source":"Value-chain Upstream", "target":"PP", "value":0.001, "optimal":"yes"} ,
{"source":"Value-chain Upstream", "target":"PLA", "value":0.001, "optimal":"yes"} ,
{"source":"Pyrolysis", "target":"Value-chain Upstream", "value":0.0255, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name": "Losses"},
{"name":"Value-chain Upstream"} 
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.5449, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4831, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.148, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0178, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.052, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1417, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.9591, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0846, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1693, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.3605, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.3196, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0979, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0118, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.1298, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.1983, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0324, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1087, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1758, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0352, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.0362, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0539, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0078, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.0092, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0018, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0008, "optimal":"yes"} ,
{"source":"Value-chain Upstream", "target":"HDPE", "value":0.001, "optimal":"yes"} ,
{"source":"Value-chain Upstream", "target":"LDPE", "value":0.001, "optimal":"yes"} ,
{"source":"Value-chain Upstream", "target":"PP", "value":0.001, "optimal":"yes"} ,
{"source":"Value-chain Upstream", "target":"PLA", "value":0.001, "optimal":"yes"} ]}; 
