let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0222, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":2.4422, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":2.3662, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0013, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2899, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.1109, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":2.2399, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1904, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0001, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0012, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0002, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.3955, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":1.8455, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.6382, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":1.015, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Lumber", "value":0.0261, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.1661, "optimal":"yes"} ]}; 
