let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0133, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":2.4422, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.8365, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0007, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":1.6051, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0667, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.6827, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0673, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0001, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0005, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0001, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1206, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.5626, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.2025, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.3094, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0506, "optimal":"yes"} ]}; 
