let dataV={"nodes": [
{"name":"Landfill"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"LABS from chemical recycling of PE"},
{"name":"C4 Gas Mixture Pyrolysis"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Lactic acid from acid hydrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.0006, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.6558, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.3415, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.8795, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1185, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.8019, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0708, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1415, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0004, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2674, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.1038, "optimal":"yes"} , 
{"source":"Segregation", "target":"C4 Gas Mixture Pyrolysis", "value":0.0009, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0477, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.226, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0002, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Lumber", "value":0.0001, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1471, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0909, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0294, "optimal":"yes"} ]}; 
