let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"LABS from chemical recycling of PE"},
{"name":"C4 Gas Mixture Pyrolysis"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0701, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6236, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0063, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0848, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.3474, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.1518, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0502, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0033, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0015, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0007, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.027, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.0656, "optimal":"yes"} , 
{"source":"Segregation", "target":"C4 Gas Mixture Pyrolysis", "value":0.0017, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0453, "optimal":"yes"} ]}; 
