let dataV={"nodes": [
{"name":"Landfill"},
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"LABS from chemical recycling of PE"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Lactic acid from acid hydrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.4722, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":1.4098, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.6585, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2234, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.5122, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1334, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.2669, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.3097, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.0019, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0007, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.9328, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1704, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.1053, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0341, "optimal":"yes"} ]}; 
