let dataV={"nodes": [
{"name":"Landfill"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"Lumber"},
{"name":"LABS from chemical recycling of PE"},
{"name":"C4 Gas Mixture Pyrolysis"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Lactic acid from acid hydrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.6649, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.0392, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.1609, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6655, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1995, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.6068, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0535, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1071, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0009, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0226, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.2344, "optimal":"yes"} , 
{"source":"Segregation", "target":"C4 Gas Mixture Pyrolysis", "value":0.0024, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.1129, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.093, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0005, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0003, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0001, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0125, "optimal":"yes"} , 
{"source":"rPP", "target":"Lumber", "value":0.0084, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0018, "optimal":"yes"} ]}; 
