let dataV={"nodes": [
{"name":"Landfill"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"LABS from chemical recycling of PE"},
{"name":"C4 Gas Mixture Pyrolysis"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.5315, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1832, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.4846, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0428, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0855, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1316, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.1391, "optimal":"yes"} , 
{"source":"Segregation", "target":"C4 Gas Mixture Pyrolysis", "value":0.0036, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0959, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0724, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0447, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0145, "optimal":"yes"} ]}; 
