let dataV={"nodes": [
{"name":"Landfill"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"Lumber"},
{"name":"LABS from chemical recycling of PE"},
{"name":"C4 Gas Mixture Pyrolysis"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Lactic acid from acid hydrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.0011, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.6903, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.0003, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.1395, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.7325, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0987, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.6678, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0589, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1179, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0007, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.3781, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0002, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.048, "optimal":"yes"} , 
{"source":"Segregation", "target":"C4 Gas Mixture Pyrolysis", "value":0.0005, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0232, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.0923, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0004, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Lumber", "value":0.0003, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0001, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.208, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.1286, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0416, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0001, "optimal":"yes"} , 
{"source":"rPP", "target":"Lumber", "value":0.0001, "optimal":"yes"} ]}; 
