let dataV={"nodes": [
{"name":"Landfill"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"LABS from chemical recycling of PE"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Lactic acid from acid hydrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.0006, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4695, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":1.4246, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.6698, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2249, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.5224, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1344, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.2687, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0004, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0141, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.2046, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0712, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.9426, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0002, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Lumber", "value":0.0001, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0078, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0048, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0016, "optimal":"yes"} ]}; 
