let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"Me-Lactate from alcoholysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0002, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.0691, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":3.7531, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":2.2592, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":1.563, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0008, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":2.0588, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1818, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.3634, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0307, "optimal":"yes"} , 
{"source":"Segregation", "target":"Me-Lactate from alcoholysis", "value":1.6648, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0169, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0104, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0034, "optimal":"yes"} ]}; 
