let dataV={"nodes": [
{"name":"Landfill"},
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"LABS from chemical recycling of PE"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Lactic acid from acid hydrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.5385, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":1.0242, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.3358, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2269, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.2179, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1075, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.215, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2703, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.052, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0181, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.6573, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1486, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0919, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0297, "optimal":"yes"} ]}; 
