let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.4788, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.3213, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.5864, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2137, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.4464, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1276, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.2553, "optimal":"yes"} , 
{"source":"Segregation", "target":"Incineration", "value":0.4199, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.9785, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2126, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.3523, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.5382, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0881, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0723, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1169, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0234, "optimal":"yes"} ]}; 
