let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.8843, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4795, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.2018, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1619, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.0958, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0967, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1934, "optimal":"yes"} , 
{"source":"Segregation", "target":"Incineration", "value":0.315, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.5851, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.3173, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.2106, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.3218, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0527, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1079, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1745, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0349, "optimal":"yes"} ]}; 
