let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.2897, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.6376, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.8173, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1101, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.7451, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0658, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1315, "optimal":"yes"} , 
{"source":"Segregation", "target":"Incineration", "value":0.2101, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.1917, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.4219, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.069, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.1054, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0173, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1435, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2321, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0464, "optimal":"yes"} ]}; 
