let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.0183, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.7099, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6417, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0864, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.585, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0516, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1033, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0121, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.4697, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0043, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0066, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0011, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1597, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2583, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0517, "optimal":"yes"} ]}; 
