let dataV={"nodes": [
{"name":"Landfill"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rPaper"},
{"name":"LABS from chemical recycling of PE"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.5587, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.5657, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":0.0035, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.994, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1339, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.9063, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.08, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.16, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.0023, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.4579, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.2007, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.0023, "optimal":"yes"} ]}; 
