let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPaper"},
{"name":"Lumber"},
{"name":"LABS from chemical recycling of PE"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Lactic acid from acid hydrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0004, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.0269, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.0528, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.1112, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":9.1724, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6314, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":8.732, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0018, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.5735, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0508, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1012, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0006, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0027, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.4626, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.0005, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0002, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.0056, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0003, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0002, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0001, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0015, "optimal":"yes"} , 
{"source":"rPP", "target":"Lumber", "value":0.001, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0002, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.4562, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.006, "optimal":"yes"} ]}; 
