let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rPaper"},
{"name":"LABS from chemical recycling of PE"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Lactic acid from acid hydrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0067, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.2104, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.6162, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.2337, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":0.0215, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.9532, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0003, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1284, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0335, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.8289, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0767, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0002, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1463, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.0136, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.3401, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.1332, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.1475, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.0134, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0002, "optimal":"yes"} ]}; 
