let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"LABS from chemical recycling of PE"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Lactic acid from acid hydrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0004, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.0021, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.6913, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.0235, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0557, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6809, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0917, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0022, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.6181, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0548, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1091, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0014, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0022, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0155, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.3127, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.1088, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.0367, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0005, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0008, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0001, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0007, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0012, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0002, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.0057, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0085, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0012, "optimal":"yes"} ]}; 
