let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"LABS from chemical recycling of PE"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.447, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2678, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.4075, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.036000000000000004, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0719, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2949, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.0281, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0098, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1003, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1622, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0324, "optimal":"yes"} ]}; 
