let dataV={"nodes": [
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.7362, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.2528, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.7529, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2361, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.7529, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1547, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":1.5301, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2228, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.5508, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.8415, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.1377, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0758, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1225, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0245, "optimal":"yes"} ]}; 
