let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6283, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0864, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.5728, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0506, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0252, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.5476, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0078, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.3012, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.1784, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0602, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.5693, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1455, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.519, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0458, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0228, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.4962, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1687, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2729, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0546, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.5693, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1455, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.519, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0458, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0228, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.4962, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1687, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2729, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0546, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.5693, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1455, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.519, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0458, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0228, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.4962, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1687, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2729, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0546, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.5693, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1455, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.519, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0458, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0228, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.4962, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1687, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2729, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0546, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.5693, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1455, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.519, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0458, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0228, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.4962, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1687, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2729, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0546, "optimal":"yes"} ]}; 
let dataV={"nodes": [
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6234, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0913, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.5684, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0502, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.025, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.5434, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1848, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2989, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0598, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6234, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0913, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.5684, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0502, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.025, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.5434, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1848, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2989, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0598, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6234, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0913, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.5684, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0502, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.025, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.5434, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1848, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2989, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0598, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6234, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0913, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.5684, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0502, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.025, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.5434, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1848, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2989, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0598, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6234, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0913, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.5684, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0502, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.025, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.5434, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1848, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2989, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0598, "optimal":"yes"} ]}; 
let dataV={"nodes": [
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.0394, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.6754, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.0359, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0032, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0016, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0343, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0117, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0189, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0038, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.0394, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.6754, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.0359, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0032, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0016, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0343, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0117, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0189, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0038, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.0394, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.6754, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.0359, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0032, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0016, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0343, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0117, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0189, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0038, "optimal":"yes"} ]}; 
let dataV={"nodes": [
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.0394, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.6754, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.0359, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0032, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0016, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0343, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0117, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0189, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0038, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.0394, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.6754, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.0359, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0032, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0016, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0343, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0117, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0189, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0038, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.0394, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.6754, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.0359, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0032, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0016, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0343, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0117, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0189, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0038, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.0394, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.6754, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.0359, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0032, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0016, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0343, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0117, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0189, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0038, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.0394, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.6754, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.0359, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0032, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0016, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0343, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0117, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0189, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0038, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.0394, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.6754, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.0359, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0032, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0016, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0343, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0117, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0189, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0038, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6299, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0848, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.5743, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0507, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0253, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.549, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0079, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.302, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.1788, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0604, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.1443, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4103, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.37, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1845, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.2491, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1102, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.055, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.879, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.3152, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.3164, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.4834, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0791, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1072, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1733, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0347, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.1443, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4103, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.37, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1845, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.2491, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1102, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.055, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.879, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.3152, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.3164, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.4834, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0791, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1072, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1733, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0347, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.1443, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4103, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.37, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1845, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.2491, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1102, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.055, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.879, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.3152, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.3164, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.4834, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0791, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1072, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1733, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0347, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.1443, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4103, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.37, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1845, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.2491, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1102, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.055, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.879, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.3152, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.3164, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.4834, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0791, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1072, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1733, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0347, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.1443, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4103, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.37, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1845, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.2491, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1102, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.055, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.879, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.3152, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.3164, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.4834, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0791, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1072, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1733, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0347, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.1443, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4103, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.37, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1845, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.2491, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1102, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.055, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.879, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.3152, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.3164, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.4834, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0791, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1072, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1733, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0347, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6299, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0848, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.5743, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0507, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0253, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.549, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0079, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.302, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.1788, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0604, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.1499, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4088, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.3736, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.185, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.2524, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1105, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0551, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.8833, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.314, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.318, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.4858, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0795, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1068, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1727, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0345, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.5919, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.2912, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.6596, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2235, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.5131, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1335, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0666, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":1.2229, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2237, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.4402, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.6726, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.1101, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.076, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.123, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0246, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.5919, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.2912, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.6596, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2235, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.5131, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1335, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0666, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":1.2229, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2237, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.4402, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.6726, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.1101, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.076, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.123, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0246, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.5919, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.2912, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.6596, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2235, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.5131, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1335, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0666, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":1.2229, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2237, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.4402, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.6726, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.1101, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.076, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.123, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0246, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.5919, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.2912, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.6596, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2235, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.5131, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1335, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0666, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":1.2229, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2237, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.4402, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.6726, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.1101, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.076, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.123, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0246, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.5919, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.2912, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.6596, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2235, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.5131, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1335, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0666, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":1.2229, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2237, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.4402, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.6726, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.1101, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.076, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.123, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0246, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6299, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0848, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.5743, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0507, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0253, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.549, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0079, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.302, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.1788, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0604, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.1499, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4088, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.3736, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.185, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.2524, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1105, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0551, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.8833, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.314, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.318, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.4858, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0795, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1068, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1727, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0345, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.6462, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.2768, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.6946, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2283, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.5451, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1364, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.068, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":1.2645, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2126, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.4552, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.6955, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.1138, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0723, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1169, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0234, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.8158, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.2316, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.8044, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.243, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.6451, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1452, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0724, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":1.3948, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1779, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.5021, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.7671, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.1255, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0605, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0979, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0196, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.8158, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.2316, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.8044, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.243, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.6451, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1452, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0724, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":1.3948, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1779, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.5021, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.7671, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.1255, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0605, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0979, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0196, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.8158, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.2316, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.8044, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.243, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.6451, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1452, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0724, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":1.3948, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1779, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.5021, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.7671, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.1255, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0605, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0979, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0196, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.8158, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.2316, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.8044, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.243, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.6451, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1452, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0724, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":1.3948, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1779, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.5021, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.7671, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.1255, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0605, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0979, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0196, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6299, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0848, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.5743, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0507, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0253, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.549, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0079, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.302, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.1788, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0604, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.1499, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4088, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.3736, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.185, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.2524, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1105, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0551, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.8833, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.314, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.318, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.4858, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0795, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1068, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1727, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0345, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.6462, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.2768, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.6946, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2283, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.5451, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1364, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.068, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":1.2645, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2126, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.4552, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.6955, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.1138, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0723, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1169, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0234, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.8943, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.2107, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.8551, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2499, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.6914, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1493, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0744, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":1.4551, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1619, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.5238, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.8003, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.131, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.055, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.089, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0178, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.9501, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.1959, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.8912, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2547, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.7243, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1522, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0759, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":1.498, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1505, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.5393, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.8239, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.1348, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0512, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0828, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0166, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.9501, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.1959, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.8912, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2547, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.7243, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1522, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0759, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":1.498, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1505, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.5393, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.8239, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.1348, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0512, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0828, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0166, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.9501, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.1959, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.8912, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2547, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.7243, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1522, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0759, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":1.498, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1505, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.5393, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.8239, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.1348, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0512, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0828, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0166, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6299, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0848, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.5743, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0507, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0253, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.549, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0079, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.302, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.1788, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0604, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.1499, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4088, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.3736, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.185, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.2524, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1105, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0551, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.8833, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.314, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.318, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.4858, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0795, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1068, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1727, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0345, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.6462, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.2768, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.6946, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2283, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.5451, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1364, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.068, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":1.2645, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2126, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.4552, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.6955, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.1138, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0723, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1169, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0234, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.8943, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.2107, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.8551, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2499, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.6914, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1493, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0744, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":1.4551, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1619, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.5238, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.8003, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.131, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.055, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.089, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0178, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":2.0396, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.1721, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.9492, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2626, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.7771, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1568, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0782, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":1.5668, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1322, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.564, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.8617, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.141, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0449, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0727, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0145, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":2.0396, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.1721, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.9492, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2626, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.7771, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1568, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0782, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":1.5668, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1322, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.564, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.8617, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.141, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0449, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0727, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0145, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":2.0396, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.1721, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.9492, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2626, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.7771, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1568, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0782, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":1.5668, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1322, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.564, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.8617, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.141, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0449, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0727, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0145, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6299, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0848, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.5743, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0507, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0253, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.549, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0079, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.302, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.1788, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0604, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.1499, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4088, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.3736, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.185, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.2524, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1105, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0551, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.8833, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.314, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.318, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.4858, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0795, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1068, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1727, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0345, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.6462, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.2768, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.6946, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2283, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.5451, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1364, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.068, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":1.2645, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2126, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.4552, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.6955, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.1138, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0723, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1169, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0234, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":1.8943, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.2107, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.8551, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2499, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.6914, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1493, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0744, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":1.4551, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1619, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.5238, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.8003, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.131, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.055, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.089, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0178, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":2.0432, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.1711, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.9514, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2629, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.7792, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.157, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0783, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":1.5695, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1315, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.565, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.8632, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.1413, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0447, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0723, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0145, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":2.1036, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.1551, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.9905, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2681, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.8148, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1602, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0799, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":1.6159, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1191, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.5817, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.8887, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.1454, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0405, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0655, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0131, "optimal":"yes"} ]}; 
let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":2.1036, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.1551, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.9905, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2681, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.8148, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1602, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0799, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":1.6159, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1191, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.5817, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.8887, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.1454, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0405, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0655, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0131, "optimal":"yes"} ]}; 
