let dataV={"nodes": [
{"name":"Landfill"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"LABS from chemical recycling of PE"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Lactic acid from acid hydrolysis"},
{"name":"Me-Lactate from alcoholysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.0012, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.6549, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.346, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.8832, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.119, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.8052, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0711, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1421, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.4149, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.0131, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0047, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.0125, "optimal":"yes"} , 
{"source":"Segregation", "target":"Me-Lactate from alcoholysis", "value":0.2164, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2282, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.1411, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0456, "optimal":"yes"} ]}; 
