let dataV={"nodes": [
{"name":"Landfill"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"LABS from chemical recycling of PE"},
{"name":"C4 Gas Mixture Pyrolysis"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Lactic acid from acid hydrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.6524, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4534, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.0906, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.2123, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.2415, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1672, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.132, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0999, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1998, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.4401, "optimal":"yes"} , 
{"source":"Segregation", "target":"C4 Gas Mixture Pyrolysis", "value":0.009, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.2399, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.1405, "optimal":"yes"} ]}; 
