let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"LABS from chemical recycling of PE"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Lactic acid from acid hydrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0003, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.0496, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.7012, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0019, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6634, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0894, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0013, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.6033, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0534, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1065, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0294, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.3212, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.1121, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.0013, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0106, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0161, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0026, "optimal":"yes"} ]}; 
