let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"LABS from chemical recycling of PE"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0014, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.0023, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.7079, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.011, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6356, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0856, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0071, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.5709, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0511, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1008, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0021, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0072, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.3178, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.1107, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0007, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0012, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0002, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.0026, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0039, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0006, "optimal":"yes"} ]}; 
