let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name":"rPaper"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0018, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.0672, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":1.226, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0094, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":0.0239, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.1346, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1919, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0091, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.0235, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0913, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1807, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0427, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.779, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.006, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.0152, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0154, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0235, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0038, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.2882, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.4284, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0623, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.0047, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0009, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0004, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.015, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0002, "optimal":"yes"} ]}; 
