let dataV={"nodes": [
{"name":"Landfill"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPaper"},
{"name":"Clinker"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.2323, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.2592, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":3.0642, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":3.1336, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.4221, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":2.8571, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.2521, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.5043, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1537, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.1715, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":2.0276, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0846, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Clinker", "value":0.0523, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0169, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0943, "optimal":"yes"} , 
{"source":"rPP", "target":"Clinker", "value":0.0635, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0137, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":1.9992, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0264, "optimal":"yes"} ]}; 
