let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name":"rPaper"},
{"name":"Compost"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.1214, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.0001, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.0425, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.0065, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0997, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":7.0269, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":6.1347, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0213, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":1.0196, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.6056, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Landfill", "value":1.3231, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":3.4977, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.4936, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.002, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Landfill", "value":0.0044, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0116, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0024, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.6194, "optimal":"yes"} , 
{"source":"Segregation", "target":"Incineration", "value":0.0269, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0171, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0026, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0348, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":2.83, "optimal":"yes"} , 
{"source":"Segregation", "target":"Compost", "value":0.0053, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0094, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0058, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0019, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0014, "optimal":"yes"} , 
{"source":"rPP", "target":"Lumber", "value":0.001, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0002, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.0272, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0052, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0024, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":2.7904, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0368, "optimal":"yes"} ]}; 
