let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPaper"},
{"name":"Compost"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0974, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.0039, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.1775, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.0723, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0051, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":6.3593, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":3.2446, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.163, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":3.2105, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.4652, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Landfill", "value":1.026, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.338, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.2611, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0223, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Landfill", "value":0.0491, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.064, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0186, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.2475, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0007, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.031, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0126, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":1.1094, "optimal":"yes"} , 
{"source":"Segregation", "target":"Compost", "value":0.0009, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0004, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Lumber", "value":0.0002, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0001, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.017, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0105, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0034, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0069, "optimal":"yes"} , 
{"source":"rPP", "target":"Lumber", "value":0.0047, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.001, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":1.0939, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0144, "optimal":"yes"} ]}; 
