let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPaper"},
{"name":"Compost"},
{"name":"Clinker"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.3878, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.0074, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.0443, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.0063, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0427, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":8.6262, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":6.5527, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0763, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":2.0979, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":1.9198, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Landfill", "value":2.0198, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.5817, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.5272, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0213, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Landfill", "value":0.0224, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0175, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0087, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.2823, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0011, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0067, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.001, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":1.3017, "optimal":"yes"} , 
{"source":"Segregation", "target":"Compost", "value":0.0064, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0006, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Clinker", "value":0.0004, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0001, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0037, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Clinker", "value":0.0023, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0007, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0005, "optimal":"yes"} , 
{"source":"rPP", "target":"Clinker", "value":0.0004, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0001, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":1.2835, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0169, "optimal":"yes"} ]}; 
