let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name":"rPaper"},
{"name":"Compost"},
{"name":"Clinker"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.3266, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4366, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.0183, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0233, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":3.8336, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":2.9759, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0318, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":1.3042, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":1.6184, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Landfill", "value":0.5554, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.1958, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.2394, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0165, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Landfill", "value":0.0056, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.002, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0036, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0349, "optimal":"yes"} , 
{"source":"Segregation", "target":"Incineration", "value":0.0001, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0165, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0007, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0002, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.1448, "optimal":"yes"} , 
{"source":"Segregation", "target":"Compost", "value":0.0007, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0091, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Clinker", "value":0.0056, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0018, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0004, "optimal":"yes"} , 
{"source":"rPP", "target":"Clinker", "value":0.0003, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0001, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.0001, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.1428, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0019, "optimal":"yes"} ]}; 
