let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"LDPE"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"rPaper"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.1328, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4413, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":2.833, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":2.8742, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0115, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.3887, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.6622, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.8259999999999998, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.2313, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0025, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0069, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0013, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.3235, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2034, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":1.306, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1119, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0692, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0224, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":1.2877, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.017, "optimal":"yes"} ]}; 
