let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name":"rPaper"},
{"name":"Compost"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0085, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.0151, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.1213, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.0334, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0424, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":8.1791, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.2359, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.2788, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":7.8767, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0201, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Landfill", "value":0.0065, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.1842, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.019, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0226, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Landfill", "value":0.0073, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.2073, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0318, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0691, "optimal":"yes"} , 
{"source":"Segregation", "target":"Incineration", "value":0.0001, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0006, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0047, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0013, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0003, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.3143, "optimal":"yes"} , 
{"source":"Segregation", "target":"Compost", "value":0.0015, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0003, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Lumber", "value":0.0002, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0001, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0026, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0016, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0005, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0007, "optimal":"yes"} , 
{"source":"rPP", "target":"Lumber", "value":0.0005, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0001, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.0001, "optimal":"yes"} , 
{"source":"rPLA", "target":"Compost", "value":0.0002, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.3099, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0041, "optimal":"yes"} ]}; 
