let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name":"rPaper"},
{"name":"Compost"},
{"name":"Clinker"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.9778, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.0011, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.1268, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.0026, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0684, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":8.3333, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":7.072, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0957, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":1.3645, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":4.8326, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Landfill", "value":0.2386, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.4029, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.569, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0623, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Landfill", "value":0.0031, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0052, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0109, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.07200000000000001, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.005, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0001, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0003, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.3282, "optimal":"yes"} , 
{"source":"Segregation", "target":"Compost", "value":0.0026, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0027, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Clinker", "value":0.0017, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0005, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0001, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0001, "optimal":"yes"} , 
{"source":"rPLA", "target":"Compost", "value":0.0003, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.3236, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0043, "optimal":"yes"} ]}; 
