let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name":"rPaper"},
{"name":"Compost"},
{"name":"Clinker"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.3182, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.006999999999999999, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.0635, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.0084, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0344, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":9.2501, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":7.2573, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.027999999999999997, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":2.0782, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":1.5871, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Landfill", "value":4.104, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.4671, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.5839, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0058, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Landfill", "value":0.0151, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0017, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0032, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0827, "optimal":"yes"} , 
{"source":"Segregation", "target":"Incineration", "value":0.0001, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0003, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0026, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0003, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0002, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.3814, "optimal":"yes"} , 
{"source":"Segregation", "target":"Compost", "value":0.0013, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0002, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Clinker", "value":0.0001, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0014, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Clinker", "value":0.0009, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0003, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0002, "optimal":"yes"} , 
{"source":"rPP", "target":"Clinker", "value":0.0001, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.0001, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.3761, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.005, "optimal":"yes"} ]}; 
