let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.1331, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.6793, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.7159, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0964, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.6528, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0576, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1152, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.088, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.4495, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0317, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0484, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0079, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1528, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2472, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0494, "optimal":"yes"} ]}; 
