let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.0108, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.7118, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6369, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0858, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.5807, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0512, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1025, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0071, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.471, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0026, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0039, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0006, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1601, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2591, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0518, "optimal":"yes"} ]}; 
