let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0291, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6272, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0027, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0848, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.1453, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.3975, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0505, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0006, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0016, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0003, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0705, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.3287, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Pyrolysis", "value":0.0784, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0333, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1808, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0362, "optimal":"yes"} ]}; 
