let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0017, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.05, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.5963, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.1861, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.4466, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.3858, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0088, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.3966, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0359, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.07, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0196, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.23399999999999999, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.073, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0071, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0108, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0018, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1287, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0796, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0257, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.0132, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0402, "optimal":"yes"} , 
{"source":"rPP", "target":"Lumber", "value":0.0138, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0058, "optimal":"yes"} ]}; 
