let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0561, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.4859, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.005, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2238, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.2782, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.1093, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0391, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0027, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0011, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0006, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0195, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0909, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Pyrolysis", "value":0.0309, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.05, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.01, "optimal":"yes"} ]}; 
