let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0549, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.6296, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.1131, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.1232, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.7582, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0049, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1028, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.2732, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.3635, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.061, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0017, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0023, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0006, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0645, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.21899999999999997, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0394, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0428, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0745, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1204, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0241, "optimal":"yes"} , 
{"source":"rPP", "target":"Pyrolysis", "value":0.0074, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.0072, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0216, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0031, "optimal":"yes"} , 
{"source":"rPLA", "target":"Pyrolysis", "value":0.0334, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0064, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.003, "optimal":"yes"} ]}; 
