let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPLA"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0272, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.0147, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.7099, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.005, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6405, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0026, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0866, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.1357, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.4212, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0515, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0005, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0016, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0003, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0746, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.006999999999999999, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.3388, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0024, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0025, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0039, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0006, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Pyrolysis", "value":0.0985, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0167, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1863, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0373, "optimal":"yes"} , 
{"source":"rPLA", "target":"Pyrolysis", "value":0.0019, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0004, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0002, "optimal":"yes"} ]}; 
