let dataV={"nodes": [
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"LABS from chemical recycling of PE"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Lactic acid from acid hydrolysis"},
{"name":"Me-Lactate from alcoholysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.0488, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.2715, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":2.5013, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":2.4866, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.3349, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":2.2672, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.2001, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0337, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2181, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.003, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0017, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.9838, "optimal":"yes"} , 
{"source":"Segregation", "target":"Me-Lactate from alcoholysis", "value":1.0259, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0186, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Lumber", "value":0.0121, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.003, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0006, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.12, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0736, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.024, "optimal":"yes"} ]}; 
