let dataV={"nodes": [
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"Lumber"},
{"name":"LABS from chemical recycling of PE"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Lactic acid from acid hydrolysis"},
{"name":"Me-Lactate from alcoholysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.0047, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4151, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.0077, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":1.709, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.8822, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2544, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.7161, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1514, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0038, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.3188, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0062, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.0101, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0035, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":1.2716, "optimal":"yes"} , 
{"source":"Segregation", "target":"Me-Lactate from alcoholysis", "value":0.1011, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0021, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Lumber", "value":0.0014, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0003, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1754, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.1084, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0351, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0034, "optimal":"yes"} , 
{"source":"rPP", "target":"Lumber", "value":0.0023, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0005, "optimal":"yes"} ]}; 
