let dataV={"nodes": [
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"Lumber"},
{"name":"LABS from chemical recycling of PE"},
{"name":"C4 Gas Mixture Pyrolysis"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Lactic acid from acid hydrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.0015, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.6467, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.0016, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.3875, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.9143, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1232, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.8336, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0736, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0012, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2767, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0013, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.1515, "optimal":"yes"} , 
{"source":"Segregation", "target":"C4 Gas Mixture Pyrolysis", "value":0.0013, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0696, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.3114, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0007, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Lumber", "value":0.0004, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0001, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1522, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0941, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0304, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0007, "optimal":"yes"} , 
{"source":"rPP", "target":"Lumber", "value":0.0005, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0001, "optimal":"yes"} ]}; 
