let dataV={"nodes": [
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"Lumber"},
{"name":"Me-Lactate from alcoholysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.5833, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.0006, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.7622, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.1859, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1602, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.0812, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0954, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.4685, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0005, "optimal":"yes"} , 
{"source":"Segregation", "target":"Me-Lactate from alcoholysis", "value":0.6122, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2577, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.1593, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0515, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0003, "optimal":"yes"} , 
{"source":"rPP", "target":"Lumber", "value":0.0002, "optimal":"yes"} ]}; 
