let dataV={"nodes": [
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"Lumber"},
{"name":"LABS from chemical recycling of PE"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Lactic acid from acid hydrolysis"},
{"name":"Me-Lactate from alcoholysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.5255, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.0048, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":1.0846, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.4231, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1917, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.2975, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1145, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2518, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0038, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.1176, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0409, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.871, "optimal":"yes"} , 
{"source":"Segregation", "target":"Me-Lactate from alcoholysis", "value":0.0005, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1385, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0856, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0277, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0021, "optimal":"yes"} , 
{"source":"rPP", "target":"Lumber", "value":0.0014, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0003, "optimal":"yes"} ]}; 
