let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rPaper"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.7528, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":9.7639, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":8.5381, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0668, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":1.1591, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":3.7408, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Landfill", "value":1.9956, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.2326, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.687, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0279, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Landfill", "value":0.0149, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0092, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0076, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.2192, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":1.0226, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":1.0083, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0133, "optimal":"yes"} ]}; 
