let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"LDPE"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"rPaper"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.4036, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4359, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":3.6069, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":3.5269, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.036000000000000004, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.4799, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":2.001, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.8149, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.2838, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0194, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0079, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0041, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1452, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0731, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.6045, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0402, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0248, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.008, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.5961, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0079, "optimal":"yes"} ]}; 
