let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rPaper"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.2001, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":8.0863, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":7.1096, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0168, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.9599, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.9996, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Landfill", "value":1.9168, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":3.3005, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.5720000000000001, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0022, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Landfill", "value":0.0043, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0074, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0019, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.5838, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":2.7241, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":2.6859, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0354, "optimal":"yes"} ]}; 
