let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"LDPE"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"rPaper"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.1889, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.127, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":5.9066, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":5.3012, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0161, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.7163, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.9428, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":3.7022, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.4265, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0027, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0107, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0018, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.6553, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0644, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":2.9933, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0354, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0219, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0071, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":2.9513, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0389, "optimal":"yes"} ]}; 
