let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"LDPE"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"rPaper"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.7289, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.1182, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":7.5607, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":6.7023, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.065, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.9116, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":3.6156, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.7729, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.5393, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0334, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0164, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0074, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.3158, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0227, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":1.4508, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0125, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0077, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0025, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":1.4305, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0189, "optimal":"yes"} ]}; 
