let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name":"rPaper"},
{"name":"Compost"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.0879, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.1592, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.9201, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0298, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":0.0655, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.1078, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1546, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.01, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0891, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1783, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0579, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1049, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.6062, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0196, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.0431, "optimal":"yes"} , 
{"source":"Segregation", "target":"Compost", "value":0.0034, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0208, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0318, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0052, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0357, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0577, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0115, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.1754, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.3334, "optimal":"yes"} , 
{"source":"rPP", "target":"Lumber", "value":0.0489, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0485, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.0119, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0029, "optimal":"yes"} , 
{"source":"rPLA", "target":"Compost", "value":0.0034, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0014, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.0425, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0006, "optimal":"yes"} ]}; 
