let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name":"rPaper"},
{"name":"Clinker"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.0381, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.3323, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.4639, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0263, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":1.015, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.4418, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.4338, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.3146, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.11599999999999999, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.23199999999999998, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.022000000000000002, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1918, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.2677, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0152, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.5858, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0079, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0121, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.002, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0311, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1055, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Clinker", "value":0.0341, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0211, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.0991, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.1473, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0214, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.0119, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0023, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0011, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.5776, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0076, "optimal":"yes"} ]}; 
