let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name":"rPaper"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0015, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.0541, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.1821, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.7992, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.3844, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":0.0058, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.232, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0239, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1695, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0072, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.1147, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0991, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0001, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0206, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0027, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.2004, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0355, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1194, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.5242, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.2521, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.0038, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0128, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0195, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0032, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0406, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0657, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0131, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.1939, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.2883, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0419, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.1966, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0378, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0176, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.0037, "optimal":"yes"} ]}; 
