let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name":"rPaper"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0055, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.3666, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.2026, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.7275, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0176, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":0.0045, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.0709, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0915, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1566, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0255, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Landfill", "value":0.0205, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.9241, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0862, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0021, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Landfill", "value":0.0017, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0752, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0104, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1764, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.2287, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1264, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.4539, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.011000000000000001, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.0028, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0823, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.1258, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0206, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.043, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0695, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0139, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.168, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.2497, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0363, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.0086, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0017, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0008, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.0028, "optimal":"yes"} ]}; 
