let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name":"rPaper"},
{"name":"Clinker"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.1705, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4115, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.3959, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.1567, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":0.066, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.0579, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1426, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.9646, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0851, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1702, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.1128, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2723, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.2619, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.1037, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.0436, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0406, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.062, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0102, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0926, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1498, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.03, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.0067, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.1441, "optimal":"yes"} , 
{"source":"rPP", "target":"Clinker", "value":0.0902, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.021, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.0809, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0156, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0073, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.043, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0006, "optimal":"yes"} ]}; 
