let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPaper"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0089, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":1.0597, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4107, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":0.2044, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.4757, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0003, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1988, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0443, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.2923, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1187, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0003, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.2281, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.6735, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.261, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.1299, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.2424, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.3704, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0606, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0888, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1436, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0287, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.1281, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0017, "optimal":"yes"} ]}; 
