let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name":"rPaper"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0122, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.1178, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.613, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.0656, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.1737, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":0.0345, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.8192, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0661, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1193, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0567, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Landfill", "value":0.0914, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.5824, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0659, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0044, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Landfill", "value":0.006999999999999999, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0447, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0075, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1107, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0605, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.3151, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0337, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0893, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.0177, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0218, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0333, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0054, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1071, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1733, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0347, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.0125, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0185, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0027, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.0697, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0134, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0063, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.0175, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0002, "optimal":"yes"} ]}; 
