let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPLA"},
{"name":"rPaper"},
{"name":"Compost"},
{"name":"Clinker"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.2127, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.6149, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0077, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":0.3823, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.0694, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0037, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1445, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Landfill", "value":0.0029, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.972, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.086, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0032, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0004, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1721, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.1403, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.4056, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0026, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.2521, "optimal":"yes"} , 
{"source":"Segregation", "target":"Compost", "value":0.0025, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0073, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0772, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Clinker", "value":0.0432, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0126, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1379, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2231, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0446, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.002, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0004, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0002, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.2486, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0033, "optimal":"yes"} ]}; 
