let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name":"rPaper"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.028999999999999998, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.5129, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.0394, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0028, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":1.5657, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.8858, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.264, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0001, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.7192, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1517, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.3034, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0191, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.3378, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0259, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0018, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":1.0311, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0069, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0105, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0017, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1149, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1858, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0372, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.0096, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0143, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0021, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.0014, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0003, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0001, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":1.0166, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0134, "optimal":"yes"} ]}; 
