let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPaper"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0028, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.0044, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.713, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":0.0048, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6302, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0001, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.092, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.013999999999999999, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.5577, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0507, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0984, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0028, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.4535, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.003, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Pyrolysis", "value":0.001, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0015, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0003, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1542, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2494, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0499, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.003, "optimal":"yes"} ]}; 
