let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPaper"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.001, "optimal":"yes"} , 
{"source":"Incineration", "target":"Landfill", "value":0.0004, "optimal":"yes"} , 
{"source":"Incineration", "target":"Losses", "value":0.0648, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.0056, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.0164, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0004, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":10.2743, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":2.5251, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0022, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":7.7695, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0049, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Incineration", "value":1.8954, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.3361, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.2032, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Incineration", "value":0.0015, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0003, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0002, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0594, "optimal":"yes"} , 
{"source":"Segregation", "target":"Incineration", "value":1.8969999999999998, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0002, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0004, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.2764, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0001, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0001, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.0002, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0002, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.2726, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0036, "optimal":"yes"} ]}; 
