let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name":"rPaper"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.2892, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.4966, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.0951, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.2926, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.7122, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":2.3509, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":3.3735, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0278, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.5461, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":1.4364, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.3525, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.2714, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0113, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0106, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0032, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.2406, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.1412, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.027000000000000003, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0832, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.2025, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.6685, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0508, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0777, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0127, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0092, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0149, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.003, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.0308, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0458, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0067, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.158, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0304, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0142, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.6592, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0087, "optimal":"yes"} ]}; 
