let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name":"rPaper"},
{"name":"Compost"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0633, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.3493, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.2822, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.5359, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0621, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":0.2802, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.2359, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0054, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2685, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.3154, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.7484, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0994, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0013, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0031, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0006, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1326, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.1432, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1157, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.2197, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0232, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.1148, "optimal":"yes"} , 
{"source":"Segregation", "target":"Compost", "value":0.0023, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0515, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0787, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0129, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0393, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0636, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0127, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.0813, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.1208, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0176, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.0181, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0035, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0016, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.1132, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0015, "optimal":"yes"} ]}; 
