let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0013, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.6758, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.0689, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6487, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.096, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0066, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.5835, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0522, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.10300000000000001, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.436, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0444, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1483, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2398, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.048, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.0164, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0244, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0036, "optimal":"yes"} ]}; 
