let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPLA"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0877, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.0072, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.7033, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0552, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6669, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0079, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0909, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.434, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.0873, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0537, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0049, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.001, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0009, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0156, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0007, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0668, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0052, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0002, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0004, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0001, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Pyrolysis", "value":0.0185, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0042, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0367, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0073, "optimal":"yes"} , 
{"source":"rPLA", "target":"Pyrolysis", "value":0.0041, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0008, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0004, "optimal":"yes"} ]}; 
