let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0192, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.0051, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.7134, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6313, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0018, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0853, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0958, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.4606, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0508, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0003, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0013, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0002, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0815, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0027, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.3777, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Pyrolysis", "value":0.001, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0015, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0002, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Pyrolysis", "value":0.0958, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2077, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0326, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0415, "optimal":"yes"} ]}; 
