let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0201, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.0225, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.6196, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.1577, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.3424, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0017, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.4558, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.1, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.1922, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0276, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0005, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0009, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0002, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0341, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0045, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1232, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0314, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0016, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0025, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0004, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0677, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0419, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0135, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.0097, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0172, "optimal":"yes"} , 
{"source":"rPP", "target":"Lumber", "value":0.0019, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0025, "optimal":"yes"} ]}; 
