let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0004, "optimal":"yes"} , 
{"source":"Incineration", "target":"Landfill", "value":0.0499, "optimal":"yes"} , 
{"source":"Incineration", "target":"Losses", "value":0.0055, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":1.4080000000000001, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.3401, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.5406, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2075, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.002, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Landfill", "value":0.6636, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Incineration", "value":0.4978, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.1967, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.124, "optimal":"yes"} , 
{"source":"Segregation", "target":"Incineration", "value":0.4978, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.1304, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0315, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.047, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0717, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0117, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0107, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0173, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0035, "optimal":"yes"} ]}; 
