let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0006, "optimal":"yes"} , 
{"source":"Incineration", "target":"Landfill", "value":0.0767, "optimal":"yes"} , 
{"source":"Incineration", "target":"Losses", "value":0.0085, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":2.6864, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":2.3675, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.3189, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.003, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Landfill", "value":1.0198, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Incineration", "value":0.765, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.3022, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1905, "optimal":"yes"} , 
{"source":"Segregation", "target":"Incineration", "value":0.765, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.2489, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0896, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.1369, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0224, "optimal":"yes"} ]}; 
