let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0004, "optimal":"yes"} , 
{"source":"Incineration", "target":"Landfill", "value":0.051, "optimal":"yes"} , 
{"source":"Incineration", "target":"Losses", "value":0.0057, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":1.4604, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.3262, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.5745, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2121, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.002, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Landfill", "value":0.6782, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Incineration", "value":0.5087, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.201, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1267, "optimal":"yes"} , 
{"source":"Segregation", "target":"Incineration", "value":0.5087, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.1353, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0302, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0487, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0744, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0122, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0103, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0166, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0033, "optimal":"yes"} ]}; 
