let dataV={"nodes": [
{"name":"Landfill"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name":"Compost"},
{"name":"Lumber"},
{"name": "Losses"},
{"name":"Value-chain Upstream"} 
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.0045, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.0107, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":1.2428, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.004, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.1122, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1498, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.014, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0895, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.179, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.003, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0071, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.8223, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0026, "optimal":"yes"} , 
{"source":"Segregation", "target":"Compost", "value":0.0021, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0017, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Lumber", "value":0.0011, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0003, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0039, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0024, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0008, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.4523, "optimal":"yes"} , 
{"source":"rPP", "target":"Lumber", "value":0.3043, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0658, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0004, "optimal":"yes"} , 
{"source":"rPLA", "target":"Compost", "value":0.0021, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0002, "optimal":"yes"} ,
{"source":"Value-chain Upstream", "target":"HDPE", "value":0.001, "optimal":"yes"} ,
{"source":"Value-chain Upstream", "target":"LDPE", "value":0.001, "optimal":"yes"} ,
{"source":"Value-chain Upstream", "target":"PP", "value":0.001, "optimal":"yes"} ,
{"source":"Value-chain Upstream", "target":"PLA", "value":0.001, "optimal":"yes"} ,
{"source":"Compost", "target":"Value-chain Upstream", "value":0.0021, "optimal":"yes"} ]}; 
