let dataV={"nodes": [
{"name":"Landfill"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"Lumber"},
{"name":"Lactic acid from acid hydrolysis"},
{"name":"Me-Lactate from alcoholysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.3468, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.0163, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":2.0855, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":2.1576, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.29100000000000004, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.9672, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1736, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.3472, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2294, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0108, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.9898, "optimal":"yes"} , 
{"source":"Segregation", "target":"Me-Lactate from alcoholysis", "value":0.3899, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1262, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.078, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0252, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0059, "optimal":"yes"} , 
{"source":"rPP", "target":"Lumber", "value":0.004, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0009, "optimal":"yes"} ]}; 
