let dataV={"nodes": [
{"name":"Landfill"},
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"LABS from chemical recycling of PE"},
{"name":"C4 Gas Mixture Pyrolysis"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Lactic acid from acid hydrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.6988, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0926, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6955, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.002, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0939, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.6341, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.055999999999999994, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0017, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0002, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1122, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.276, "optimal":"yes"} , 
{"source":"Segregation", "target":"C4 Gas Mixture Pyrolysis", "value":0.0034, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.1409, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.0613, "optimal":"yes"} ]}; 
