let dataV={"nodes": [
{"name":"Landfill"},
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"Lactic acid from acid hydrolysis"},
{"name":"Me-Lactate from alcoholysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.2279, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":2.83, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":2.1918, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.8662, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.9983, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1764, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.3527, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1226, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.4604, "optimal":"yes"} , 
{"source":"Segregation", "target":"Me-Lactate from alcoholysis", "value":1.0626, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0675, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0417, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0135, "optimal":"yes"} ]}; 
