let dataV={"nodes": [
{"name":"Landfill"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"LABS from chemical recycling of PE"},
{"name":"C4 Gas Mixture Pyrolysis"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Lactic acid from acid hydrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7053, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.0019, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0486, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6659999999999999, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0897, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.6072, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0536, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1072, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.2828, "optimal":"yes"} , 
{"source":"Segregation", "target":"C4 Gas Mixture Pyrolysis", "value":0.0033, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.1401, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.0321, "optimal":"yes"} ]}; 
