let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPLA"},
{"name":"LABS from chemical recycling of PE"},
{"name":"C4 Gas Mixture Pyrolysis"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0003, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.0049, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.7132, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0011, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.4782, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.24100000000000002, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0016, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.4341, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0385, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0766, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0024, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0273, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0005, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.1704, "optimal":"yes"} , 
{"source":"Segregation", "target":"C4 Gas Mixture Pyrolysis", "value":0.0044, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.1171, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Pyrolysis", "value":0.0009, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0013, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0002, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Pyrolysis", "value":0.0093, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.015, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.003, "optimal":"yes"} , 
{"source":"rPLA", "target":"Pyrolysis", "value":0.0004, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0001, "optimal":"yes"} ]}; 
