let dataV={"nodes": [
{"name":"Landfill"},
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"LABS from chemical recycling of PE"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Lactic acid from acid hydrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.332, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":2.2252, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":2.2528, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0008, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.3036, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":2.0540000000000003, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1813, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0007, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0001, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.3626, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1952, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.0169, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0059, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":1.4724, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1073, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0664, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0215, "optimal":"yes"} ]}; 
