let dataV={"nodes": [
{"name":"Landfill"},
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"Lactic acid from acid hydrolysis"},
{"name":"Me-Lactate from alcoholysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.0013, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":4.1475, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":3.6563, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.4925, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":3.3336, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.2942, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.5884, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0009, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":1.5361, "optimal":"yes"} , 
{"source":"Segregation", "target":"Me-Lactate from alcoholysis", "value":1.2082, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0005, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0003, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0001, "optimal":"yes"} ]}; 
