let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPaper"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.1069, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.5517, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.085, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":0.7942, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.3332, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2047, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.2155, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1073, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.2145, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0696, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.3591, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0553, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.5169, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0383, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Lumber", "value":0.0251, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0063, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1221, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1975, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0395, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0304, "optimal":"yes"} , 
{"source":"rPP", "target":"Lumber", "value":0.0205, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0044, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.5097, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0067, "optimal":"yes"} ]}; 
