let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name":"rPaper"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0005, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.1004, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.5755, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.1876, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0101, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":0.0448, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6638, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.1193, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1353, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0023, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.6025, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0534, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0004, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.1031, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0136, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1245, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0635, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.3641, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.1187, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0064, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.0284, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0229, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0349, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0057, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1238, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2003, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0401, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.0439, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0653, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0095, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.005, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.001, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0004, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.027999999999999997, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0004, "optimal":"yes"} ]}; 
