let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.3939, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.6099, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.8846, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1192, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.8066, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0712, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1424, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.2606, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.4036, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0938, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.1433, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0235, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1372, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.222, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0444, "optimal":"yes"} ]}; 
