let dataV={"nodes": [
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"Lactic acid from acid hydrolysis"},
{"name":"Me-Lactate from alcoholysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.0128, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4243, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":1.6684, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.8556, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2499, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.6918, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1493, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0103, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.341, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.1412, "optimal":"yes"} , 
{"source":"Segregation", "target":"Me-Lactate from alcoholysis", "value":1.1994, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0057, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Lumber", "value":0.0037, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0009, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1875, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.1159, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0375, "optimal":"yes"} ]}; 
