let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"Lactic acid from acid hydrolysis"},
{"name":"Me-Lactate from alcoholysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0001, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4203, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":1.7116, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.8789, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2531, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0003, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.7127, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1512, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.3376, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.6534, "optimal":"yes"} , 
{"source":"Segregation", "target":"Me-Lactate from alcoholysis", "value":0.7217, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1857, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.1148, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0371, "optimal":"yes"} ]}; 
