let dataV={"nodes": [
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"Lactic acid from acid hydrolysis"},
{"name":"Me-Lactate from alcoholysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.0001, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.247, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":2.7187, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":2.6138, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.3521, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":2.3831, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.2103, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0001, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1985, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.7678, "optimal":"yes"} , 
{"source":"Segregation", "target":"Me-Lactate from alcoholysis", "value":1.4167, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0001, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1092, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0675, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0218, "optimal":"yes"} ]}; 
