let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"LABS from chemical recycling of PE"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Me-Lactate from alcoholysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0023, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.0285, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4068, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":1.7463, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.9226, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.259, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0117, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.7388, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1547, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0227, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.3166, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.0053, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0018, "optimal":"yes"} , 
{"source":"Segregation", "target":"Me-Lactate from alcoholysis", "value":1.3919, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0125, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Lumber", "value":0.0082, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.002, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1741, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.1076, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0348, "optimal":"yes"} ]}; 
