let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0183, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.6867, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.024, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0837, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.5853, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0015, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2077, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0916, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.4237, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0471, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0002, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.001, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0002, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.075, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.3024, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0106, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0369, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.049, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1663, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0538, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0333, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.0039, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0058, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0008, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.0288, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0055, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0026, "optimal":"yes"} ]}; 
