let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.2337, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.1794, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.0628, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":2.906, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.6202, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0211, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":1.5069, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":1.1558, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.0906, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1304, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0143, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0011, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0024, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0162, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0043, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0015, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0697, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0015, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0024, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0005, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.0006, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0008, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0001, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.0544, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0105, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0049, "optimal":"yes"} ]}; 
