let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0214, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4959, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.3815, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0187, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.2626, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0018, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.6318, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.1064, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.1117, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0211, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0007, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0007, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0002, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0198, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0512, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0394, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0019, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0282, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0174, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0056, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.0024, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0217, "optimal":"yes"} , 
{"source":"rPP", "target":"Lumber", "value":0.0121, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0032, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.0015, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0003, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0001, "optimal":"yes"} ]}; 
