let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name":"rPaper"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0172, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.6712, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4821, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.006, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0415, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":0.4115, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.4035, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0012, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2077, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0862, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.1761, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1129, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0001, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0009, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0001, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.2078, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.4035, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2899, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0036, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.025, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.2474, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.1453, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.2219, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0363, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Pyrolysis", "value":0.0157, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0829, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1594, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0319, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.002, "optimal":"yes"} , 
{"source":"rPP", "target":"Lumber", "value":0.0013, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0003, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.0195, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0037, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0017, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.244, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0032, "optimal":"yes"} ]}; 
