let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPaper"},
{"name":"Compost"},
{"name":"Clinker"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.2181, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.6197, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0003, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":0.3369, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.0287, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0039, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1424, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.938, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0828, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0034, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0004, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1661, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.1439, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.4088, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.2223, "optimal":"yes"} , 
{"source":"Segregation", "target":"Compost", "value":0.0002, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0518, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0791, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.013000000000000001, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.135, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2249, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Clinker", "value":0.004, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.045, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.2192, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0029, "optimal":"yes"} ]}; 
