let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"rPLA"},
{"name":"rPaper"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.629, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.3908, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":0.1696, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.0482, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1412, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Landfill", "value":0.0077, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.9475, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0843, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1672, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.4126, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.2564, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.1113, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1331, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2269, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0072, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0454, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.2, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0385, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0179, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.1097, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0014, "optimal":"yes"} ]}; 
