let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPLA"},
{"name":"rPaper"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0855, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.0346, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.6225, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.2834, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":0.3902, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.1376, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0075, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1855, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.4255, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.5267, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0915, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0027, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0033, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0009, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0935, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0113, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2042, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.09300000000000001, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.128, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0041, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0062, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.001, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0694, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1123, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0225, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.0725, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0139, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0065, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.1262, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0017, "optimal":"yes"} ]}; 
