let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name":"rPaper"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.0917, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4775, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.3154, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.1518, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":0.0783, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.9696, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.145, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.884, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.078, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.156, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0599, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.3119, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.20600000000000002, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0991, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.0511, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0329, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Lumber", "value":0.0216, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0054, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0845, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1715, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0216, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0343, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.1133, "optimal":"yes"} , 
{"source":"rPP", "target":"Lumber", "value":0.0762, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0165, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.0773, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0149, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0069, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.0504, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0007, "optimal":"yes"} ]}; 
