let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name":"rPaper"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0046, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.3451, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.0296, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0258, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":4.9817, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.431, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0001, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":4.9510000000000005, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0231, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Landfill", "value":0.005, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.3601, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0347, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0001, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0636, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.019, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0016, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0014, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.2746, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Pyrolysis", "value":0.0065, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0105, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0021, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.0006, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0009, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0001, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.0011, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0002, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0001, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.2707, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0036, "optimal":"yes"} ]}; 
