let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name":"rPaper"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0147, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.0887, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4685, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.3517, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.1115, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":0.045, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.9304, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0011, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1339, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0734, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.7603, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0749, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0001, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0008, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0001, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1343, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0522, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2756, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.2069, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0656, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.0265, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0188, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0287, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0047, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0937, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1516, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0303, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.0766, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.1138, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0166, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.0512, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0098, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0046, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.0261, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0003, "optimal":"yes"} ]}; 
