let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPLA"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0136, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.0324, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.7045, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0093, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6566, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.001, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0886, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0682, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Landfill", "value":0.0308, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.4843, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0528, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0001, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0007, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0001, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0856, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0173, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.3771, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.005, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0062, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0095, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0016, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1282, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2074, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0415, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.0039, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0007, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0003, "optimal":"yes"} ]}; 
