let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"rPLA"},
{"name":"rPaper"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.4415, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0171, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":3.8319, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.3661, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":3.9244, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.3338, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0295, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0589, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0283, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0011, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.2455, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0156, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0096, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0031, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.0009, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0002, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0001, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.2421, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0032, "optimal":"yes"} ]}; 
