let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.1806, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.6667, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.7467, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1006, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.6808, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0601, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1202, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.1195, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.4411, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.043, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0657, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0108, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.15, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2426, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0485, "optimal":"yes"} ]}; 
