let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0022, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.5, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.5641, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.0295, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0053, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.9679, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.131, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0109, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.8694, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0779, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1535, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.3258, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.3675, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0192, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0034, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.1173, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.1792, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0293, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.125, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2021, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0404, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.0071, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0106, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0015, "optimal":"yes"} , 
{"source":"rPLA", "target":"Pyrolysis", "value":0.0027, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0005, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0002, "optimal":"yes"} ]}; 
