let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.3492, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.6218, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.8558, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1153, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.7802, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0689, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1377, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.2311, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.4114, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0832, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.1271, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0208, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1399, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2263, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0453, "optimal":"yes"} ]}; 
