let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"rPaper"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"Incineration", "target":"Landfill", "value":0.0012, "optimal":"yes"} , 
{"source":"Incineration", "target":"Losses", "value":0.0593, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.0626, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":9.5446, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":2.3601, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":7.2471, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Incineration", "value":1.7409, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.3517, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1899, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0621, "optimal":"yes"} , 
{"source":"Segregation", "target":"Incineration", "value":1.7409, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0019, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.2877, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.001, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0006, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0002, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.2837, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0037, "optimal":"yes"} ]}; 
