let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0102, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.2382, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0009, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.4757, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.051, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.156, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0192, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0002, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0005, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0001, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0276, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1289, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Pyrolysis", "value":0.0254, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0709, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0184, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0142, "optimal":"yes"} ]}; 
