let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"C4 Gas Mixture Pyrolysis"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0407, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6263, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0035, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0848, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.2026, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.32799999999999996, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0504, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0011, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0018, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0004, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0582, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2352, "optimal":"yes"} , 
{"source":"Segregation", "target":"C4 Gas Mixture Pyrolysis", "value":0.002, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0262, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1294, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.08, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0259, "optimal":"yes"} ]}; 
