let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"C4 Gas Mixture Pyrolysis"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0538, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6251, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0047, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0848, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.2673, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.2493, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0503, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0019, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0018, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0005, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0443, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1783, "optimal":"yes"} , 
{"source":"Segregation", "target":"C4 Gas Mixture Pyrolysis", "value":0.0016, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0205, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0981, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0606, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0196, "optimal":"yes"} ]}; 
