let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0346, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.3707, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0031, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.341, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.172, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.1316, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0298, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0014, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.001, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0004, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0234, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1092, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Pyrolysis", "value":0.0371, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0601, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.012, "optimal":"yes"} ]}; 
