let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"C4 Gas Mixture Pyrolysis"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0087, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6292, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0006, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0848, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0433, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.5217, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0506, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0005, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0001, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0922, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.4263, "optimal":"yes"} , 
{"source":"Segregation", "target":"C4 Gas Mixture Pyrolysis", "value":0.0002, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0027, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2345, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.1449, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0469, "optimal":"yes"} ]}; 
