let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"C4 Gas Mixture Pyrolysis"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0142, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.0271, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.6638, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.0774, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6756, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0014, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0912, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.071, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.5308, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0544, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0001, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0011, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0002, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0939, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0154, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.3131, "optimal":"yes"} , 
{"source":"Segregation", "target":"C4 Gas Mixture Pyrolysis", "value":0.0102, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0753, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Pyrolysis", "value":0.0051, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0085, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Lumber", "value":0.0005, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0014, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Pyrolysis", "value":0.1065, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1722, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0344, "optimal":"yes"} ]}; 
