let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0365, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6267, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0032, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0848, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.1818, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Landfill", "value":0.0177, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.3345, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0504, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0009, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Landfill", "value":0.0001, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0016, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0004, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0593, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2759, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0007, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0001, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1518, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0937, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0304, "optimal":"yes"} ]}; 
