let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPLA"},
{"name":"Lumber"},
{"name":"C4 Gas Mixture Pyrolysis"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0058, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.004, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.7128, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0051, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.6359, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0004, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.0857, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0288, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.5452, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0512, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0003, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0963, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0025, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.4408, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0032, "optimal":"yes"} , 
{"source":"Segregation", "target":"C4 Gas Mixture Pyrolysis", "value":0.0002, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.002, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Pyrolysis", "value":0.0009, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0014, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0002, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Pyrolysis", "value":0.0038, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2424, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.1461, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0485, "optimal":"yes"} , 
{"source":"rPLA", "target":"Pyrolysis", "value":0.0025, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0005, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0002, "optimal":"yes"} ]}; 
