let dataV={"nodes": [
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"Lumber"},
{"name":"LABS from chemical recycling of PE"},
{"name":"C4 Gas Mixture Pyrolysis"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Lactic acid from acid hydrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.5382, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.0004, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":1.025, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.3779, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1856, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.2563, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1109, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0526, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0003, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.2602, "optimal":"yes"} , 
{"source":"Segregation", "target":"C4 Gas Mixture Pyrolysis", "value":0.0002, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0925, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.8236, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0289, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0179, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0058, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0002, "optimal":"yes"} , 
{"source":"rPP", "target":"Lumber", "value":0.0001, "optimal":"yes"} ]}; 
