let dataV={"nodes": [
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"LABS from chemical recycling of PE"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Lactic acid from acid hydrolysis"},
{"name":"Me-Lactate from alcoholysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.2119, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":2.923, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":2.7628, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.3721, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":2.5189, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.2223, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0688, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.07, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0244, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":1.9903, "optimal":"yes"} , 
{"source":"Segregation", "target":"Me-Lactate from alcoholysis", "value":0.3583, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0378, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0234, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0076, "optimal":"yes"} ]}; 
