let dataV={"nodes": [
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"LABS from chemical recycling of PE"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Lactic acid from acid hydrolysis"},
{"name":"Me-Lactate from alcoholysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.3289, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":2.2428, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":2.2664, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.3053, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":2.0664, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1824, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2132, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.0352, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0123, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.4193, "optimal":"yes"} , 
{"source":"Segregation", "target":"Me-Lactate from alcoholysis", "value":1.3829, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1173, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0725, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0235, "optimal":"yes"} ]}; 
