let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPaper"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.001, "optimal":"yes"} , 
{"source":"Incineration", "target":"Landfill", "value":0.0172, "optimal":"yes"} , 
{"source":"Incineration", "target":"Losses", "value":0.0373, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.2711, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.3614, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":3.8981, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.5784, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":3.3929, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.5593, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0007, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Landfill", "value":0.2542, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Incineration", "value":0.1833, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.0738, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0465, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0041, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Landfill", "value":1.4196, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Incineration", "value":1.0239, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.4124, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.3866, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0858, "optimal":"yes"} , 
{"source":"Segregation", "target":"Incineration", "value":1.2072, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.024, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0319, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.3445, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0086, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0132, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0022, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0109, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0176, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0035, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.3397, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0045, "optimal":"yes"} ]}; 
