let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.2889, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.6378, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.8168, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.11, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.7447, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0657, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1314, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.1912, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.4221, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0688, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.1052, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0172, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1435, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2321, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0464, "optimal":"yes"} ]}; 
