let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name":"rPaper"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0175, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.1092, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.5578, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.1589, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0724, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":0.2472, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.9486, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.038, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1588, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0844, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.7636, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0763, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0032, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0292, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0043, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1399, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0622, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.3179, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0906, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0412, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.1409, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0224, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0342, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0056, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.1081, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1749, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.035, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.0335, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0498, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0072, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.0322, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0062, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0029, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.1389, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0018, "optimal":"yes"} ]}; 
