let dataV={"nodes": [
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name":"rPaper"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.0211, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4867, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.1572, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.1612, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":0.9943, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.4847, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.3359, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.3536, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1195, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.2389, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0129, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.298, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0963, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0987, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.6088, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0047, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0071, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0012, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0983, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1639, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.003, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0328, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.0356, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0529, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0077, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.077, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0148, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0069, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.6003, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0079, "optimal":"yes"} ]}; 
