let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name":"rPaper"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0149, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.9073, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.2702, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.33799999999999997, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0158, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":0.0889, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.4269, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0009, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1923, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0745, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Landfill", "value":0.0008, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.2107, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1148, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0007, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0001, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.2138, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.5587, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1664, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.2081, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.0097, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.0547, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.2011, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.3073, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.0503, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0566, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0915, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0183, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.077, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.1145, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0166, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.0076, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.0015, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0007, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.054000000000000006, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0007, "optimal":"yes"} ]}; 
