let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0019, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.0001, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":0.0002, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.0154, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.6996, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0094, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.0027, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0012, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.0005, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0022, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0008, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0012, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0002, "optimal":"yes"} ]}; 
