let dataV={"nodes": [
{"name":"Pyrolysis"},
{"name":"Landfill"},
{"name":"Incineration"},
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Paper"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"rPLA"},
{"name":"rPaper"},
{"name":"Lumber"},
{"name": "Losses"}
],
 "links": [
 {"source":"Pyrolysis", "target":"Losses", "value":0.0143, "optimal":"yes"} , 
{"source":"HDPE", "target":"Households", "value":0.2129, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4219, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.2898, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.396, "optimal":"yes"} , 
{"source":"Paper", "target":"Households", "value":0.0422, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.1319, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.001, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2299, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Pyrolysis", "value":0.0717, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.946, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0911, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Pyrolysis", "value":0.0001, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0008, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0001, "optimal":"yes"} , 
{"source":"Segregation", "target":"Landfill", "value":0.1671, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.1218, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2413, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.1658, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPLA", "value":0.2266, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPaper", "value":0.0242, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Incineration", "value":0.0438, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.067, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.011000000000000001, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Incineration", "value":0.0414, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1327, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0407, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0265, "optimal":"yes"} , 
{"source":"rPP", "target":"Incineration", "value":0.0613, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0912, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0133, "optimal":"yes"} , 
{"source":"rPLA", "target":"Incineration", "value":0.1767, "optimal":"yes"} , 
{"source":"rPLA", "target":"PLA", "value":0.034, "optimal":"yes"} , 
{"source":"rPLA", "target":"Losses", "value":0.0159, "optimal":"yes"} , 
{"source":"rPaper", "target":"Paper", "value":0.0238, "optimal":"yes"} , 
{"source":"rPaper", "target":"Losses", "value":0.0003, "optimal":"yes"} ]}; 
