let dataV={"nodes": [
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"LABS from chemical recycling of PE"},
{"name":"C4 Gas Mixture Pyrolysis"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Lactic acid from acid hydrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.6354, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.4612, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.9664, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1302, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.8811, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0778, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.1894, "optimal":"yes"} , 
{"source":"Segregation", "target":"C4 Gas Mixture Pyrolysis", "value":0.002, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0918, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.3705, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.11, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.068, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.022000000000000002, "optimal":"yes"} ]}; 
