let dataV={"nodes": [
{"name":"HDPE"},
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rHDPE"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"Lumber"},
{"name":"Lactic acid from acid hydrolysis"},
{"name":"Me-Lactate from alcoholysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"HDPE", "target":"Households", "value":0.016, "optimal":"yes"} , 
{"source":"LDPE", "target":"Households", "value":0.4168, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.0063, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":1.6868, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.6401, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.4857, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.4954, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.132, "optimal":"yes"} , 
{"source":"Segregation", "target":"rHDPE", "value":0.0112, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2932, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0044, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.0072, "optimal":"yes"} , 
{"source":"Segregation", "target":"Me-Lactate from alcoholysis", "value":1.1794, "optimal":"yes"} , 
{"source":"rHDPE", "target":"HDPE", "value":0.0062, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Lumber", "value":0.004, "optimal":"yes"} , 
{"source":"rHDPE", "target":"Losses", "value":0.001, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1612, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0997, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0322, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0024, "optimal":"yes"} , 
{"source":"rPP", "target":"Lumber", "value":0.0016, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0004, "optimal":"yes"} ]}; 
