let dataV={"nodes": [
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"LABS from chemical recycling of PE"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Me-Lactate from alcoholysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.5852, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":0.7532, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.1795, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1589, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.0754, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0949, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.4024, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.0468, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0163, "optimal":"yes"} , 
{"source":"Segregation", "target":"Me-Lactate from alcoholysis", "value":0.6052, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.2213, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.1368, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0443, "optimal":"yes"} ]}; 
