let dataV={"nodes": [
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"LABS from chemical recycling of PE"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Clay reycled PLA"},
{"name":"Lactic acid from acid hydrolysis"},
{"name":"Me-Lactate from alcoholysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.0501, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":3.8638, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":3.4492, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.4646, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":3.1448, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.2775, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.0278, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0097, "optimal":"yes"} , 
{"source":"Segregation", "target":"Clay reycled PLA", "value":0.0524, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.3759, "optimal":"yes"} , 
{"source":"Segregation", "target":"Me-Lactate from alcoholysis", "value":2.6763, "optimal":"yes"} ]}; 
