let dataV={"nodes": [
{"name":"LDPE"},
{"name":"PP"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"rPP"},
{"name":"Lumber"},
{"name":"LABS from chemical recycling of PE"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Lactic acid from acid hydrolysis"},
{"name":"Me-Lactate from alcoholysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.3162, "optimal":"yes"} , 
{"source":"PP", "target":"Households", "value":0.004, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":2.3035, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":2.3067, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.317, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":2.1031, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1856, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2505, "optimal":"yes"} , 
{"source":"Segregation", "target":"rPP", "value":0.0032, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.002, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0007, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":1.5396, "optimal":"yes"} , 
{"source":"Segregation", "target":"Me-Lactate from alcoholysis", "value":0.3068, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1378, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0852, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0276, "optimal":"yes"} , 
{"source":"rPP", "target":"PP", "value":0.0017, "optimal":"yes"} , 
{"source":"rPP", "target":"Lumber", "value":0.0012, "optimal":"yes"} , 
{"source":"rPP", "target":"Losses", "value":0.0003, "optimal":"yes"} ]}; 
