let dataV={"nodes": [
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"LABS from chemical recycling of PE"},
{"name":"C4 Gas Mixture Pyrolysis"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.5148, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.1999, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.4693, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0414, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1345, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.1741, "optimal":"yes"} , 
{"source":"Segregation", "target":"C4 Gas Mixture Pyrolysis", "value":0.0045, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.1201, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.07400000000000001, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0457, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0148, "optimal":"yes"} ]}; 
