let dataV={"nodes": [
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"LABS from chemical recycling of PE"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Lactic acid from acid hydrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.511, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":1.1844, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.4941, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2013, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.3622, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1202, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.0972, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.2162, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0752, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.9516, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0535, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0331, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0107, "optimal":"yes"} ]}; 
