let dataV={"nodes": [
{"name":"LDPE"},
{"name":"PLA"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"LABS from chemical recycling of PE"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name":"Lactic acid from acid hydrolysis"},
{"name":"Me-Lactate from alcoholysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.4396, "optimal":"yes"} , 
{"source":"PLA", "target":"Households", "value":1.5997, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":1.7971, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.2421, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":1.6385, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.1446, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.2556, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.0673, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0234, "optimal":"yes"} , 
{"source":"Segregation", "target":"Lactic acid from acid hydrolysis", "value":0.4951, "optimal":"yes"} , 
{"source":"Segregation", "target":"Me-Lactate from alcoholysis", "value":0.7903, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.1406, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.0869, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0281, "optimal":"yes"} ]}; 
