let dataV={"nodes": [
{"name":"LDPE"},
{"name":"Households"},
{"name":"Curbside Collection"},
{"name":"Dropoff"},
{"name":"Segregation"},
{"name":"rLDPE"},
{"name":"Lumber"},
{"name":"LABS from chemical recycling of PE"},
{"name":"C4 Gas Mixture Pyrolysis"},
{"name":"Light Liquid Fuel Pyrolysis"},
{"name": "Losses"}
],
 "links": [
 {"source":"LDPE", "target":"Households", "value":0.7147, "optimal":"yes"} , 
{"source":"Households", "target":"Curbside Collection", "value":0.408, "optimal":"yes"} , 
{"source":"Households", "target":"Dropoff", "value":0.0009, "optimal":"yes"} , 
{"source":"Households", "target":"Losses", "value":0.3058, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Segregation", "value":0.37200000000000005, "optimal":"yes"} , 
{"source":"Curbside Collection", "target":"Losses", "value":0.0328, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Segregation", "value":0.0008, "optimal":"yes"} , 
{"source":"Dropoff", "target":"Losses", "value":0.0001, "optimal":"yes"} , 
{"source":"Segregation", "target":"rLDPE", "value":0.1352, "optimal":"yes"} , 
{"source":"Segregation", "target":"LABS from chemical recycling of PE", "value":0.1235, "optimal":"yes"} , 
{"source":"Segregation", "target":"C4 Gas Mixture Pyrolysis", "value":0.0032, "optimal":"yes"} , 
{"source":"Segregation", "target":"Light Liquid Fuel Pyrolysis", "value":0.0852, "optimal":"yes"} , 
{"source":"rLDPE", "target":"LDPE", "value":0.0744, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Lumber", "value":0.046, "optimal":"yes"} , 
{"source":"rLDPE", "target":"Losses", "value":0.0149, "optimal":"yes"} ]}; 
